import XCTest
@testable import CyberpunkMonsterCrawl

/// Covers this PR's two load-bearing pieces of new engineering:
///
/// - **AC2 (chunk-boundary agreement):** a tile generated as part of a
///   chunk must be identical to the same world tile generated standalone
///   via `CityLatticeGenerator.classify`. Per `CityLatticeGenerator`'s own
///   docs this is true *by construction* (it is a pure function of
///   `(tileX, tileY, seed)` with no neighbour lookups), so this test is
///   deliberately a thin wrapper assertion rather than a search for subtle
///   bugs \u2014 exactly as the ticket's implementation notes describe.
/// - **Footprint-reservation no-overlap:** `Chunk.reserve` must refuse a
///   footprint that would overlap an already-reserved one, and must still
///   allow a genuinely disjoint reservation to succeed.
/// - **Placement-surface polarity:** reservation happens on
///   `Chunk.placementSurface` (`.buildingFootprint`, the ~3-in-4 block
///   interiors the lattice fills with buildings) and is refused on both
///   street tiles and the deliberately empty `.lot` blocks. That polarity is
///   easy to invert, so it is pinned in both directions here.
final class ChunkGeneratorTests: XCTestCase {

    // MARK: - AC2: chunk-embedded generation agrees with standalone `classify`

    func test_chunkTiles_matchStandaloneClassify_atChunkEdgesAcrossMultipleChunkPairs() {
        let seeds: [WorldSeed] = [WorldSeed(rawValue: 1), WorldSeed(rawValue: 999_999), WorldSeed(rawValue: 42)]
        let chunkCoordinates = [
            ChunkCoordinate(x: 0, y: 0),
            ChunkCoordinate(x: 1, y: 0),
            ChunkCoordinate(x: 0, y: 1),
            ChunkCoordinate(x: -1, y: 0),
            ChunkCoordinate(x: 0, y: -1),
            ChunkCoordinate(x: -1, y: -1),
            ChunkCoordinate(x: 3, y: -2)
        ]

        for seed in seeds {
            for chunkCoordinate in chunkCoordinates {
                let chunk = ChunkGenerator.generate(chunkCoordinate: chunkCoordinate, seed: seed)
                let origin = chunkCoordinate.worldTileOrigin

                // Every edge/corner local coordinate: (0, 0) is where this
                // chunk sits directly against its lower-index neighbours;
                // (size-1, size-1) is where it sits against its
                // higher-index neighbours. Together with the two mixed
                // corners, this exercises every boundary this chunk shares.
                let edgeLocalCoordinates = [
                    (0, 0), (Chunk.size - 1, Chunk.size - 1),
                    (0, Chunk.size - 1), (Chunk.size - 1, 0),
                    (7, 3), (3, 7)
                ]

                for (localX, localY) in edgeLocalCoordinates {
                    let embedded = chunk.tile(localX: localX, localY: localY)
                    let standalone = CityLatticeGenerator.classify(
                        tileX: origin.tileX + localX,
                        tileY: origin.tileY + localY,
                        seed: seed
                    )
                    XCTAssertEqual(
                        embedded, standalone,
                        "Chunk \(chunkCoordinate) local (\(localX), \(localY)) under seed \(seed.rawValue) "
                            + "disagreed with standalone classify"
                    )
                }
            }
        }
    }

    func test_chunkTiles_matchStandaloneClassify_everyTileInChunk() {
        // A denser sweep than the edges-only test above: every one of the
        // 64 tiles in a handful of chunks, so a bug that only shows up mid-
        // chunk (not just at the boundary) would still be caught.
        let seed = WorldSeed(rawValue: 31_337)
        let chunkCoordinates = [ChunkCoordinate(x: 0, y: 0), ChunkCoordinate(x: -2, y: 5)]

        for chunkCoordinate in chunkCoordinates {
            let chunk = ChunkGenerator.generate(chunkCoordinate: chunkCoordinate, seed: seed)
            let origin = chunkCoordinate.worldTileOrigin

            for localX in 0..<Chunk.size {
                for localY in 0..<Chunk.size {
                    let embedded = chunk.tile(localX: localX, localY: localY)
                    let standalone = CityLatticeGenerator.classify(
                        tileX: origin.tileX + localX,
                        tileY: origin.tileY + localY,
                        seed: seed
                    )
                    XCTAssertEqual(embedded, standalone)
                }
            }
        }
    }

    // MARK: - Block ownership: every block generated by exactly one chunk

    /// The rule that replaced "only blocks whose whole interior fits in this
    /// chunk". That rule dropped ~44% of building blocks (`Chunk.size` 8 is
    /// not a multiple of `CityLatticeGenerator.period` 6, so per axis only 3
    /// of every 4 interiors fit inside one chunk, ~9/16 in 2D), leaving
    /// buildingless holes no consumer could trace back to generation.
    ///
    /// Ownership must therefore be a *partition*: sweeping a region of
    /// chunks yields every block whose interior lands in it, each exactly
    /// once — no block dropped, no block emitted twice.
    func test_blockCoordinates_ownedByChunk_partitionTheBlocksTheChunksCover() {
        let chunkRange = -3...3
        var claimingChunks: [BlockCoordinate: [ChunkCoordinate]] = [:]

        for chunkX in chunkRange {
            for chunkY in chunkRange {
                let chunkCoordinate = ChunkCoordinate(x: chunkX, y: chunkY)
                let owned = BuildingPlacement.blockCoordinates(ownedByChunk: chunkCoordinate)
                XCTAssertFalse(
                    owned.isEmpty,
                    "Chunk \(chunkCoordinate) owns no block at all — an 8-tile span always contains "
                        + "at least one multiple of the 6-tile period."
                )
                XCTAssertEqual(Set(owned).count, owned.count, "Chunk \(chunkCoordinate) listed a block twice.")

                for block in owned {
                    claimingChunks[block, default: []].append(chunkCoordinate)
                    XCTAssertEqual(
                        block.owningChunk, chunkCoordinate,
                        "Block \(block) was offered by \(chunkCoordinate) but its owner is \(block.owningChunk)."
                    )
                }
            }
        }

        // Nothing claimed twice.
        for (block, chunks) in claimingChunks {
            XCTAssertEqual(
                chunks.count, 1,
                "Block \(block) was claimed by \(chunks.count) chunks (\(chunks)) — records would be duplicated."
            )
        }

        // Nothing dropped: chunks (-3...3) cover world tiles -24..<32, so
        // every block whose interior origin (`block * 6`) lands in that span
        // — i.e. every block in -4...5 on each axis — must have been claimed.
        for blockX in -4...5 {
            for blockY in -4...5 {
                let block = BlockCoordinate(x: blockX, y: blockY)
                XCTAssertNotNil(
                    claimingChunks[block],
                    "Block \(block) intersects the swept chunk region but no chunk claimed it."
                )
            }
        }

        // The specific case the old rule dropped: block (1, 1)'s interior
        // spans tiles 6...8, straddling the seam between chunks (0, 0) and
        // (1, 1). It must still have exactly one owner.
        XCTAssertEqual(BlockCoordinate(x: 1, y: 1).owningChunk, ChunkCoordinate(x: 0, y: 0))
        XCTAssertEqual(claimingChunks[BlockCoordinate(x: 1, y: 1)]?.count, 1)
    }

    /// The end-to-end consequence of the partition: sweeping a region of
    /// generated chunks reproduces every block's placements exactly once,
    /// including the seam-straddling blocks, and every building block ends
    /// up with all 9 of its interior lots covered.
    func test_generate_acrossASweptRegion_everyBuildingBlockGetsAllNineLots_exactlyOnce() {
        let seed = WorldSeed(rawValue: 4_711)
        var sweptRecords: [BuildingPlacementRecord] = []

        for chunkX in -3...3 {
            for chunkY in -3...3 {
                let chunk = ChunkGenerator.generate(chunkCoordinate: ChunkCoordinate(x: chunkX, y: chunkY), seed: seed)
                sweptRecords.append(contentsOf: chunk.buildingPlacements)
            }
        }

        let recordsByLot = Dictionary(grouping: sweptRecords, by: \.lotTile)
        var buildingBlockCount = 0
        var expectedRecordCount = 0

        for blockX in -4...5 {
            for blockY in -4...5 {
                let block = BlockCoordinate(x: blockX, y: blockY)
                let expected = BuildingPlacement.generate(forBlock: block, seed: seed)
                expectedRecordCount += expected.count
                guard !expected.isEmpty else { continue }
                buildingBlockCount += 1

                XCTAssertEqual(
                    Set(expected.flatMap(\.footprintTiles)).count,
                    CityLatticeGenerator.blockSize * CityLatticeGenerator.blockSize,
                    "Block \(block) does not have its whole 3x3 interior covered."
                )

                for record in expected {
                    let emitted = recordsByLot[record.lotTile] ?? []
                    XCTAssertEqual(
                        emitted.count, 1,
                        "Lot \(record.lotTile) of block \(block) was emitted \(emitted.count) times across the "
                            + "swept chunks — expected exactly one owning chunk."
                    )
                    if let emittedRecord = emitted.first {
                        XCTAssertEqual(
                            emittedRecord, record,
                            "Lot \(record.lotTile) was emitted with a different building than generating "
                                + "block \(block) directly produces."
                        )
                    }
                }
            }
        }

        XCTAssertGreaterThan(buildingBlockCount, 50, "Sample too small to claim the coverage gap is closed.")
        XCTAssertEqual(
            sweptRecords.count, expectedRecordCount,
            "The swept chunks emitted a different number of placements than the blocks they own."
        )
    }

    // MARK: - Building-footprint reservation: no overlap

    /// Finds the first `WorldSeed` under which block `(blockX: 0, blockY: 0)`
    /// — world tiles `(0...2, 0...2)`, fully inside chunk `(0, 0)` — is a
    /// *building* block, so these tests have a guaranteed 3x3 patch of
    /// `Chunk.placementSurface` (`.buildingFootprint`) tiles to reserve
    /// against rather than depending on luck with a single hardcoded seed.
    private func seedWithBuildingBlockAtOriginBlock() -> WorldSeed {
        for rawSeed in UInt64(0)..<500 {
            let seed = WorldSeed(rawValue: rawSeed)
            if !CityLatticeGenerator.isEmptyLotBlock(blockX: 0, blockY: 0, seed: seed) {
                return seed
            }
        }
        XCTFail("Expected at least one seed in 0..<500 to make block (0, 0) a building block")
        return WorldSeed(rawValue: 0)
    }

    /// A chunk built straight from `CityLatticeGenerator.classify`, with a
    /// fresh empty store and **without** `ChunkGenerator.generate`'s
    /// placement fold.
    ///
    /// The `Chunk.reserve` / `reservableFootprints(in:)` tests below are unit
    /// tests of the reservation API itself, and a *generated* chunk no longer
    /// leaves a free building-block tile to reserve: generation fills every
    /// lot of every block the chunk owns and folds those footprints into the
    /// store (covered separately by the fold tests). Building the chunk
    /// directly keeps these tests aimed at the API rather than at whichever
    /// buildings the seed happened to place.
    private func unplacedChunk(at chunkCoordinate: ChunkCoordinate, seed: WorldSeed) -> Chunk {
        let origin = chunkCoordinate.worldTileOrigin
        let tiles: [[TileInfo]] = (0..<Chunk.size).map { localX in
            (0..<Chunk.size).map { localY in
                CityLatticeGenerator.classify(
                    tileX: origin.tileX + localX,
                    tileY: origin.tileY + localY,
                    seed: seed
                )
            }
        }
        return Chunk(origin: chunkCoordinate, tiles: tiles)
    }

    /// The mirror of the above: a seed under which block `(0, 0)` is one of
    /// the ~1-in-4 blocks the brief leaves empty, used to pin that `.lot`
    /// tiles are *not* reservable.
    private func seedWithEmptyLotAtOriginBlock() -> WorldSeed {
        for rawSeed in UInt64(0)..<500 {
            let seed = WorldSeed(rawValue: rawSeed)
            if CityLatticeGenerator.isEmptyLotBlock(blockX: 0, blockY: 0, seed: seed) {
                return seed
            }
        }
        XCTFail("Expected at least one seed in 0..<500 to make block (0, 0) an empty lot")
        return WorldSeed(rawValue: 0)
    }

    func test_reserve_twoByTwoFootprint_blocksOverlappingReservations_butAllowsDisjointOnes() {
        let seed = seedWithBuildingBlockAtOriginBlock()
        let chunk = unplacedChunk(at: ChunkCoordinate(x: 0, y: 0), seed: seed)

        // Sanity: the 3x3 block interior this test relies on is really the
        // placement surface under this seed.
        for tileX in 0..<3 {
            for tileY in 0..<3 {
                XCTAssertEqual(chunk.tile(localX: tileX, localY: tileY).kind, Chunk.placementSurface)
            }
        }

        // First reservation: a 2x2 footprint at the block's corner succeeds.
        XCTAssertTrue(chunk.reserve(footprint: .twoByTwo, at: TileCoordinate(tileX: 0, tileY: 0)))

        // Any footprint overlapping the tiles just claimed (0,0)-(1,1) must
        // be refused, whether it's a 1x1 fully inside it or a 2x2 that only
        // partially overlaps it.
        XCTAssertFalse(
            chunk.reserve(footprint: .oneByOne, at: TileCoordinate(tileX: 1, tileY: 1)),
            "A 1x1 footprint inside an already-reserved 2x2 must be refused"
        )
        XCTAssertFalse(
            chunk.reserve(footprint: .twoByTwo, at: TileCoordinate(tileX: 1, tileY: 0)),
            "A 2x2 footprint overlapping an already-reserved 2x2 must be refused"
        )

        // A genuinely disjoint 1x1 footprint elsewhere in the same building
        // block must still succeed — refusing overlaps must not turn into
        // refusing everything.
        XCTAssertTrue(
            chunk.reserve(footprint: .oneByOne, at: TileCoordinate(tileX: 2, tileY: 2)),
            "A footprint disjoint from the existing reservation should be allowed"
        )
    }

    func test_reservableFootprints_excludesTilesCoveredByAnExistingReservation() {
        let seed = seedWithBuildingBlockAtOriginBlock()
        let chunk = unplacedChunk(at: ChunkCoordinate(x: 0, y: 0), seed: seed)

        let beforeReservation = Set(chunk.reservableFootprints(in: .oneByOne))
        XCTAssertTrue(beforeReservation.contains(TileCoordinate(tileX: 1, tileY: 1)))

        XCTAssertTrue(chunk.reserve(footprint: .twoByTwo, at: TileCoordinate(tileX: 0, tileY: 0)))

        let afterReservation = Set(chunk.reservableFootprints(in: .oneByOne))
        XCTAssertFalse(
            afterReservation.contains(TileCoordinate(tileX: 1, tileY: 1)),
            "A tile already claimed by a reservation must not still be offered as reservable"
        )
        XCTAssertTrue(
            afterReservation.contains(TileCoordinate(tileX: 2, tileY: 2)),
            "A tile outside the existing reservation, still the placement surface, must remain reservable"
        )
    }

    // MARK: - Placements fold into the world-lifetime reservation store

    /// `LotReservationStore` stays the single truth about occupied tiles:
    /// every footprint `ChunkGenerator.generate` places is folded into it, so
    /// `chunk.reservedTiles` is non-empty for a chunk full of buildings
    /// instead of the two systems silently disagreeing.
    func test_generate_foldsEveryPlacedFootprintIntoTheWorldLifetimeStore() {
        let seed = seedWithBuildingBlockAtOriginBlock()
        let store = LotReservationStore()
        let chunk = ChunkGenerator.generate(
            chunkCoordinate: ChunkCoordinate(x: 0, y: 0),
            seed: seed,
            reservations: store
        )

        XCTAssertFalse(chunk.buildingPlacements.isEmpty, "Seed was chosen to make block (0, 0) a building block.")
        XCTAssertFalse(
            chunk.reservedTiles.isEmpty,
            "A chunk full of buildings reported no reserved tiles — the placement fold is missing."
        )

        for record in chunk.buildingPlacements {
            for tile in record.footprintTiles {
                XCTAssertTrue(
                    store.isReserved(tile),
                    "Tile \(tile) is covered by a placed building but is not reserved in the store."
                )
            }
        }
    }

    /// The consequence that motivated the fold: `reservableFootprints(in:)`
    /// must never offer a tile a placed building is standing on.
    func test_generate_reservableFootprints_neverOffersATileAPlacedBuildingOccupies() {
        let seed = seedWithBuildingBlockAtOriginBlock()
        let chunk = ChunkGenerator.generate(chunkCoordinate: ChunkCoordinate(x: 0, y: 0), seed: seed)

        let occupied = Set(chunk.buildingPlacements.flatMap(\.footprintTiles))
        XCTAssertFalse(occupied.isEmpty)

        for size in BuildingFootprintSize.allCases {
            for offered in chunk.reservableFootprints(in: size) {
                XCTAssertFalse(
                    occupied.contains(offered),
                    "\(size) footprint origin \(offered) is offered as reservable but a building occupies it."
                )
            }
        }

        // Chunk (0, 0)'s every `.buildingFootprint` tile belongs to one of the
        // four blocks it owns, and placement fills each such block's whole
        // interior — so after the fold nothing in this chunk is reservable at
        // all. That is the honest state of the world, not a bug: the lots are
        // taken.
        XCTAssertTrue(
            chunk.reservableFootprints(in: .oneByOne).isEmpty,
            "Every placement-surface tile of this chunk carries a building, so none may be offered."
        )
    }

    /// The fold has to be safe on the eviction/regeneration path the store
    /// exists for: placement is a pure function of `(block, seed)` and the
    /// store is a set, so re-folding an already-folded chunk changes nothing.
    func test_generate_foldIntoTheStore_isIdempotentAcrossRegeneration() {
        let seed = seedWithBuildingBlockAtOriginBlock()
        let store = LotReservationStore()
        let chunkCoordinate = ChunkCoordinate(x: 0, y: 0)

        _ = ChunkGenerator.generate(chunkCoordinate: chunkCoordinate, seed: seed, reservations: store)
        let afterFirstGeneration = store.allReservedTiles
        XCTAssertFalse(afterFirstGeneration.isEmpty)

        for _ in 0..<3 {
            _ = ChunkGenerator.generate(chunkCoordinate: chunkCoordinate, seed: seed, reservations: store)
        }

        XCTAssertEqual(
            store.allReservedTiles,
            afterFirstGeneration,
            "Regenerating an evicted chunk must re-fold exactly the same tiles, never accumulate new ones."
        )
    }

    /// A block owned by one chunk may spill its footprint over the seam, so a
    /// neighbour sharing the world-lifetime store sees those tiles as
    /// reserved — the cross-chunk visibility the fold buys.
    func test_generate_neighbouringChunksSharingAStore_seeEachOthersPlacedFootprints() {
        let seed = WorldSeed(rawValue: 4_711)
        let store = LotReservationStore()

        var placedTiles: Set<TileCoordinate> = []
        for chunkX in 0...1 {
            for chunkY in 0...1 {
                let chunk = ChunkGenerator.generate(
                    chunkCoordinate: ChunkCoordinate(x: chunkX, y: chunkY),
                    seed: seed,
                    reservations: store
                )
                placedTiles.formUnion(chunk.buildingPlacements.flatMap(\.footprintTiles))
            }
        }

        XCTAssertFalse(placedTiles.isEmpty)
        for tile in placedTiles {
            XCTAssertTrue(store.isReserved(tile), "Tile \(tile) was placed on but is not reserved in the store.")
        }
    }

    // MARK: - Placement-surface polarity

    func test_reserve_refusesFootprintOnStreetTile() {
        // Street tiles are structurally guaranteed at (3...5) mod 6 on
        // either axis regardless of seed, so tile (3, 0) is street under
        // every seed — no need to search for one.
        let seed = WorldSeed(rawValue: 12_345)
        let chunk = ChunkGenerator.generate(chunkCoordinate: ChunkCoordinate(x: 0, y: 0), seed: seed)

        XCTAssertNotEqual(chunk.tile(localX: 3, localY: 0).kind, Chunk.placementSurface)
        XCTAssertFalse(chunk.reserve(footprint: .oneByOne, at: TileCoordinate(tileX: 3, tileY: 0)))
    }

    func test_placementSurface_isTheBuildingBlockInterior_notTheDeliberatelyEmptyLot() {
        // Polarity guard. `.lot` marks the ~1-in-4 blocks the brief leaves
        // empty, so a footprint must never be offered or accepted there;
        // buildings belong in the ~3-in-4 `.buildingFootprint` interiors.
        XCTAssertEqual(Chunk.placementSurface, .buildingFootprint)

        let emptyLotSeed = seedWithEmptyLotAtOriginBlock()
        let emptyLotChunk = ChunkGenerator.generate(chunkCoordinate: ChunkCoordinate(x: 0, y: 0), seed: emptyLotSeed)
        XCTAssertEqual(emptyLotChunk.tile(localX: 1, localY: 1).kind, .lot)
        XCTAssertFalse(
            emptyLotChunk.reserve(footprint: .oneByOne, at: TileCoordinate(tileX: 1, tileY: 1)),
            "A footprint must never be reservable inside a deliberately empty .lot block"
        )
        XCTAssertFalse(
            emptyLotChunk.reservableFootprints(in: .oneByOne).contains(TileCoordinate(tileX: 1, tileY: 1)),
            "An empty .lot tile must never be offered as a reservable footprint origin"
        )

        let buildingSeed = seedWithBuildingBlockAtOriginBlock()
        let buildingChunk = unplacedChunk(at: ChunkCoordinate(x: 0, y: 0), seed: buildingSeed)
        XCTAssertTrue(
            buildingChunk.reservableFootprints(in: .oneByOne).contains(TileCoordinate(tileX: 1, tileY: 1)),
            "A building-block interior tile must be offered as a reservable footprint origin"
        )
    }

    func test_reservedFootprint_isSolidByConstruction_withoutAnyTileKindTransition() {
        // The other half of the polarity contract: because the placement
        // surface is already the not-walkable kind, a reserved footprint
        // collides without `Chunk` having to mutate any tile, so collision
        // consumers can keep reading `isWalkable` alone.
        let seed = seedWithBuildingBlockAtOriginBlock()
        let chunk = unplacedChunk(at: ChunkCoordinate(x: 0, y: 0), seed: seed)

        XCTAssertTrue(chunk.reserve(footprint: .twoByTwo, at: TileCoordinate(tileX: 0, tileY: 0)))
        for localX in 0..<2 {
            for localY in 0..<2 {
                XCTAssertFalse(
                    chunk.tile(localX: localX, localY: localY).isWalkable,
                    "A reserved footprint tile must be solid without needing a TileKind transition"
                )
            }
        }
        XCTAssertFalse(Chunk.placementSurface.isWalkable)
    }
}
