import Foundation

/// Wraps `CityLatticeGenerator.classify` into 8x8 `Chunk`s.
///
/// The whole point of this type is that it adds *nothing* beyond
/// packaging: `generate` iterates exactly the chunk's own 8x8 world-tile
/// footprint and calls `classify` once per tile, with no neighbour lookups
/// and no chunk-local state feeding back into the classification. Because
/// `classify` is a pure function of `(tileX, tileY, seed)` alone
/// (`CityLatticeGenerator`'s own contract), a tile generated here is
/// byte-for-byte identical to the same tile generated standalone \u2014 that
/// equivalence is what `ChunkGeneratorTests`'s boundary-agreement test
/// pins (AC2), and it is true by construction rather than by careful
/// bookkeeping.
enum ChunkGenerator {
    /// Generates the chunk at `chunkCoordinate` under `seed`: every tile in
    /// its 8x8 world-tile footprint, classified independently.
    ///
    /// `reservations` is the building-footprint reservation store the new
    /// chunk reads and writes through. It defaults to a fresh private store
    /// (so a standalone call still yields a self-contained chunk), but
    /// `ChunkStreamingManager` passes its own world-lifetime store, which is
    /// what makes a reservation survive eviction and regeneration — tile
    /// content is reproduced by `classify`, reservations cannot be.
    static func generate(
        chunkCoordinate: ChunkCoordinate,
        seed: WorldSeed,
        reservations: LotReservationStore = LotReservationStore()
    ) -> Chunk {
        let worldOrigin = chunkCoordinate.worldTileOrigin

        let tiles: [[TileInfo]] = (0..<Chunk.size).map { localX in
            (0..<Chunk.size).map { localY in
                CityLatticeGenerator.classify(
                    tileX: worldOrigin.tileX + localX,
                    tileY: worldOrigin.tileY + localY,
                    seed: seed
                )
            }
        }

        // Building/rooftop-sign placement (`CYBERPUN-17-5-t1`) is decided
        // per *block*, not per chunk, and is a pure function of
        // `(blockCoordinate, seed)` — so this is not "generation" the way
        // `tiles` above is; it's aggregation of an already-pure decision
        // onto the chunk that owns it.
        //
        // Ownership is `BuildingPlacement.blockCoordinates(ownedByChunk:)`:
        // every block whose interior lower corner lands in this chunk, which
        // partitions the plane so each block is generated by exactly one
        // chunk. A "fully contained interior only" rule would instead drop
        // ~44% of building blocks on the floor — `Chunk.size` (8) is not a
        // multiple of `CityLatticeGenerator.period` (6), so per axis only 3
        // of every 4 interiors fit inside one chunk, ~9/16 in 2D — and there
        // is nothing to gain by dropping them: `generate(forBlock:seed:)`
        // reads nothing but `(block, seed)`, so unlike
        // `Chunk.reservableFootprints(in:)` (which must consult `tiles` for a
        // `TileKind` visible only inside its own chunk) there is no
        // cross-chunk lookup here to avoid.
        var buildingPlacements: [BuildingPlacementRecord] = []
        var roofSigns: [RooftopSignRecord] = []
        for block in BuildingPlacement.blockCoordinates(ownedByChunk: chunkCoordinate) {
            let placements = BuildingPlacement.generate(forBlock: block, seed: seed)
            buildingPlacements.append(contentsOf: placements)
            if let sign = RooftopSignPlacement.generate(forBlock: block, placements: placements, seed: seed) {
                roofSigns.append(sign)
            }
        }

        // Fold the placements into the world-lifetime `LotReservationStore`,
        // so that store stays the single truth about which tiles are
        // occupied. Without this, `chunk.reservedTiles` would be empty even
        // for a chunk packed with buildings and
        // `Chunk.reservableFootprints(in:)` would hand a later consumer
        // (props, spawn points, the next placement story) a tile a building
        // is already standing on.
        //
        // Idempotent by construction, which is what makes it safe on the
        // eviction/regeneration path: `BuildingPlacement.generate` is a pure
        // function of `(block, seed)`, so regenerating this chunk produces
        // the identical tiles, and `LotReservationStore.reserve` is a set
        // union. Reserving directly (rather than through `Chunk.reserve`)
        // is deliberate: these tiles are already validated by construction —
        // they are block-interior tiles, i.e. `Chunk.placementSurface` — and
        // a block owned by this chunk may legitimately spill its footprint
        // across the chunk seam, which `Chunk.reserve`'s chunk-local bounds
        // check would refuse.
        reservations.reserve(buildingPlacements.flatMap(\.footprintTiles))

        return Chunk(
            origin: chunkCoordinate,
            tiles: tiles,
            reservations: reservations,
            buildingPlacements: buildingPlacements,
            roofSigns: roofSigns
        )
    }
}
