import CoreGraphics
import SpriteKit

/// Mounts the ground plane into `GameScene.worldLayer`: the production
/// consumer of `GroundTileRenderer`, driven by `ChunkStreamingManager`'s
/// resident chunk window.
///
/// `GroundTileRenderer.node(for:at:)` is a factory, and a factory with no
/// caller renders nothing in a real build — the story's headline AC ("render
/// every generated ground cell", product gate 4: *the city has to read as a
/// city*) is only observable once something parents those nodes into the
/// scene. This is that something.
///
/// ## `CYBERPUN-17-5-t2`: buildings mount here too
///
/// The same argument applies verbatim to
/// `TileFieldRenderer.makeBuildingNode(for:)`. `Chunk.buildingPlacements` is
/// generated by `ChunkGenerator` (`CYBERPUN-17-5-t1`), and a building factory
/// nothing calls leaves the other half of product gate 4 ("the city reads as
/// a city ... building sprites placed across the blocks") unreachable in a
/// real build no matter how green the unit tests that call the factory
/// directly are. So this mount walks each newly resident chunk's
/// `buildingPlacements` in the same pass that mounts its ground tiles,
/// parents the building nodes into the same `worldLayer`, and drops them
/// through the same eviction bookkeeping. Actors and camera-following still
/// land later (`CYBERPUN-17-6`/`CYBERPUN-17-7`) and will mount into this same
/// layer alongside these nodes.
///
/// ## `CYBERPUN-17-5-t3`: rooftop signs mount as building children
///
/// `Chunk.roofSigns` follows the same "a factory nothing calls renders
/// nothing in a real build" argument: `mountChunk` attaches each signed
/// lot's `RooftopSignRenderer.makeSignNode(for:parent:)` node as a child of
/// its carrier building node, in the same pass that mounts the building
/// itself. A sign therefore has no bookkeeping of its own here — no
/// `signNodesByChunk` map, no separate pool — because a child node's
/// lifecycle already follows its parent building node's: it mounts when the
/// building mounts, and it is torn down (and, for a pooled building node,
/// stripped before the pool reuses it — see `dequeueOrMakeBuildingNode`)
/// exactly when the building is.
///
/// **Node ownership mirrors chunk residency.** One ground node per tile, plus
/// one building node per `buildingPlacements` record, of every resident
/// chunk; when `ChunkStreamingManager` evicts a chunk, this drops both sets
/// of that chunk's nodes in the same pass. The resident window is a fixed size
/// (`ChunkStreamingManager.residentWindowSize`), so the mounted node count is
/// bounded however far the camera roams — the scene-graph counterpart of AC8,
/// and pinned by `GroundPlaneStreamerTests`.
///
/// Nodes are parented **directly** under `worldLayer` (no intermediate
/// container) because `GroundTileRenderer` sets a `worldLayer`-*relative*
/// `zPosition`: SpriteKit accumulates `zPosition` down the tree, so an
/// intermediate node with any non-zero `zPosition` would silently shift every
/// ground tile out of the depth scheme `DepthModel` computed.
///
/// ## `CYBERPUN-17-4-t4`: mounting is incremental, on every call
///
/// A runtime probe reported "PLAY tapped, screen never visibly left the
/// menu"; the cause was that `updateCamera` used to build/mount every tile of
/// the entire resident window (up to
/// `ChunkStreamingManager.residentWindowSize * Chunk.size * Chunk.size` =
/// 3,136 `SKSpriteNode`s) inside the same call stack as the PLAY tap — real,
/// uninterrupted main-thread work with no yield point.
///
/// The rule now is uniform and has no "first call" special case:
/// - Chunks within `ChunkStreamingManager.quickstartRadius` of the camera
///   **mount synchronously**. That ring is sized (and test-pinned) to cover
///   the viewport, so it is the part that may already be on screen and
///   therefore the part that cannot be deferred without a visible hole.
/// - Everything beyond it — off-screen by construction — is appended to
///   `pendingMountQueue` and mounted a few chunks at a time by
///   `advanceIncrementalMount()`, which `GameScene.update(_:)` calls every
///   frame.
///
/// Applying the same split to *every* call, rather than only the first, is
/// deliberate. An earlier revision of this fix mounted the whole window
/// synchronously on every call after the first, which was harmless only
/// because nothing in Release calls `updateCamera` a second time today —
/// `CYBERPUN-17-7` ("wire the thumbstick, player movement and camera") makes
/// camera-follow call it *every frame*, and the very next frame after the
/// quickstart mount would have folded the entire deferred remainder into one
/// frame, reinstating exactly the stall this type exists to avoid. The
/// bounded-synchronous-work property has to hold for the frame-driven camera
/// too, so it is stated per call rather than per instance.
///
/// **What is deferred is mounting, not generation.** `updateCamera` calls
/// `ChunkStreamingManager.updateCamera` first, and that generates every chunk
/// of the resident window (49 chunks x `Chunk.size`^2 tiles, plus their
/// `LotReservationStore` decisions) synchronously, in this call. Only
/// `SKSpriteNode` creation/`addChild` for the chunks outside the quickstart
/// ring is deferred. So this fix removes the scene-graph half of the PLAY-tap
/// stall and not the world-generation half; anyone debugging a residual stall
/// on entry to `.gameplay` should look at generation next (deferring
/// residency itself — widening from the quickstart ring to `residentRadius`
/// as the queue drains — is the shape that would cover both halves).
final class GroundPlaneStreamer {

    /// Streams the chunk window this mount follows. Owned here (rather than
    /// injected from the scene) so the ground plane has exactly one source of
    /// truth for "which tiles exist right now".
    let streaming: ChunkStreamingManager

    /// The world seed `streaming` generates from. Exposed so a caller
    /// restarting a run (`GameScene.startGroundPlane()`) can tell whether the
    /// mounted city is still the right one and keep this streamer — along
    /// with its `pool` and its already-generated chunks — instead of building
    /// a replacement whose pool starts empty.
    let seed: WorldSeed

    /// The layer ground nodes are parented into. Weak: the scene owns the
    /// layer, and this mount must never keep a dead scene's graph alive.
    private weak var worldLayer: SKNode?

    /// Mounted nodes, grouped by the chunk whose residency they follow, so an
    /// eviction is an O(tiles-per-chunk) removal rather than a full rescan.
    private var nodesByChunk: [ChunkCoordinate: [SKSpriteNode]] = [:]

    /// Mounted **building** nodes, grouped the same way and mounted/evicted
    /// in the same passes as `nodesByChunk` (`CYBERPUN-17-5-t2`). Kept as a
    /// separate map rather than folded into `nodesByChunk` so the ground
    /// plane's own bounded-count and recycling invariants stay stated about
    /// ground tiles - one per resident tile, a fixed number - while a
    /// chunk's building count varies with how many block interiors it owns.
    ///
    /// A chunk's records may legitimately place a footprint across a chunk
    /// seam (`Chunk.buildingPlacements`' doc comment), so these are keyed by
    /// the *owning* chunk, exactly as generation is; that keeps mount and
    /// eviction symmetric and stops two neighbouring chunks from both
    /// mounting the same building.
    private var buildingNodesByChunk: [ChunkCoordinate: [SKSpriteNode]] = [:]

    /// Chunks that are currently resident (`streaming.residentChunks`) but
    /// not yet mounted, nearest-to-the-camera first — everything outside the
    /// quickstart ring, queued by `updateCamera` and drained by
    /// `advanceIncrementalMount()`. Empty once the deferred remainder has
    /// fully landed, which in steady state is the normal condition.
    private var pendingMountQueue: [ChunkCoordinate] = []

    /// Chunks currently waiting for the incremental mount. Exposed so tests
    /// can assert the deferral itself (and its drain) rather than only its
    /// visible consequences.
    var pendingMountCount: Int { pendingMountQueue.count }

    /// How many queued chunks `advanceIncrementalMount()` mounts per call.
    /// `GameScene.update(_:)` calls it once per frame, so this is also "how
    /// many chunks stream in per frame" while a deferred remainder drains.
    /// Small enough that a single tick's mounting work cannot itself become a
    /// visible stall (each chunk is `Chunk.size * Chunk.size` = 64 sprite
    /// configurations — a small fraction of the ~3,136-node pass this exists
    /// to avoid), large enough that the full window still lands within a
    /// handful of frames.
    static let defaultChunksPerIncrementalMountTick = 6

    /// Nodes this mount has given up — because their chunk streamed out of
    /// the resident window, or because `unmountAll()` tore the whole window
    /// down — held here for reuse rather than deallocated.
    ///
    /// `CYBERPUN-17-4-t3`: without this, every chunk that streams in would
    /// allocate a fresh `SKSpriteNode` per tile, so panning far enough would
    /// have allocated and discarded many multiples of the resident window's
    /// worth of nodes even though only `mountedNodeCount` are ever on screen
    /// at once.
    ///
    /// **The invariant, scoped to what actually holds.** For a given
    /// `GroundPlaneStreamer` instance, after the window has been filled from
    /// empty once (which, since `CYBERPUN-17-4-t4`, is spread across the
    /// incremental mount rather than done in a single call), no further
    /// ground `SKSpriteNode` is allocated by either supported call sequence
    /// (building nodes have their own `buildingPool` with the same property,
    /// so mounting buildings did not weaken this):
    /// - *Panning.* Eviction runs (in `synchroniseWithResidentChunks`)
    ///   *before* anything is mounted or queued in the same `updateCamera`
    ///   call, and the resident window is a fixed size, so the nodes freed by
    ///   eviction on any call are exactly what that call's mount — and the
    ///   drain of what it queued — needs.
    /// - *`unmountAll()` then `updateCamera`* (what a restarted run does).
    ///   `unmountAll()` returns every node it detaches to this pool rather
    ///   than dropping it, and it leaves `streaming.residentChunks` alone, so
    ///   the re-mount asks for exactly the window's worth the pool is now
    ///   holding. Both paths are pinned by `ChunkStreamingGroundTests`.
    ///
    /// Because mounting is deferred but eviction is not, the pool now holds a
    /// chunk's nodes for the few frames between "streamed out" and "the drain
    /// reaches the chunk that reuses them" instead of handing them over
    /// within the same call. That is still bounded by one resident window's
    /// worth, which is what the invariant claims.
    ///
    /// The invariant is per instance and cannot be otherwise: a brand-new
    /// `GroundPlaneStreamer` starts with an empty pool by construction, so a
    /// caller that discards this object discards the pool with it. That is
    /// why `GameScene.startGroundPlane()` keeps the existing streamer when
    /// the run's seed is unchanged instead of building a fresh one per run.
    ///
    /// Capped defensively at `maxPoolSize` regardless, so a call pattern the
    /// reasoning above doesn't cover still can't grow memory without bound.
    private var pool: [SKSpriteNode] = []

    /// Building nodes freed by eviction (or by `unmountAll()`), parked for
    /// reuse by a later mount. Separate from `pool` because the two are
    /// reconfigured by different renderers - `GroundTileRenderer.configure`
    /// vs `TileFieldRenderer.configure` - and a node handed to the wrong one
    /// would be re-textured as the wrong kind of content.
    ///
    /// Same bound and same reasoning as `pool`: eviction runs before any
    /// mounting in a call, and both the resident window and a chunk's
    /// placement count are fixed for a given `(coordinate, seed)`, so a pan
    /// recycles rather than allocates. Capped defensively at `maxPoolSize`
    /// too.
    private var buildingPool: [SKSpriteNode] = []

    /// Nodes currently parked in the recycle pool. Exposed for the tests that
    /// pin the invariant on `pool`'s doc comment (notably the
    /// `unmountAll()` -> `updateCamera` sequence, where the pool is what
    /// stands between a restarted run and a whole window of fresh
    /// allocations).
    var pooledNodeCount: Int { pool.count }

    /// Defensive cap on `pool`'s size — see `pool`'s doc comment for why it
    /// should never need to hold more than one resident window's worth.
    private static var maxPoolSize: Int { ChunkStreamingManager.residentWindowSize * Chunk.size * Chunk.size }

    init(seed: WorldSeed, worldLayer: SKNode) {
        self.seed = seed
        self.streaming = ChunkStreamingManager(seed: seed)
        self.worldLayer = worldLayer
    }

    /// Chunks currently mounted in the scene graph.
    var mountedChunks: Set<ChunkCoordinate> { Set(nodesByChunk.keys) }

    /// Total ground nodes currently in the scene graph. Bounded by
    /// `ChunkStreamingManager.residentWindowSize * Chunk.size * Chunk.size`.
    ///
    /// Deliberately still ground-only: `worldLayer.children.count` is this
    /// plus `mountedBuildingNodeCount` since `CYBERPUN-17-5-t2`, and every
    /// "one node per resident tile" assertion is about this number.
    var mountedNodeCount: Int { nodesByChunk.values.reduce(0) { $0 + $1.count } }

    /// Total building nodes currently in the scene graph: one per
    /// `Chunk.buildingPlacements` record of every resident chunk.
    var mountedBuildingNodeCount: Int { buildingNodesByChunk.values.reduce(0) { $0 + $1.count } }

    /// Building nodes currently parked in `buildingPool`, exposed for the
    /// same reason `pooledNodeCount` is.
    var pooledBuildingNodeCount: Int { buildingPool.count }

    /// Moves the camera to `worldPosition` (tile space) and brings the scene
    /// graph back in step with chunk residency: removes the nodes of every
    /// chunk that was just evicted, mounts every newly resident chunk inside
    /// the `ChunkStreamingManager.quickstartRadius` ring, and queues the rest
    /// for `advanceIncrementalMount()`.
    ///
    /// Idempotent for a camera that hasn't left its chunk — the streaming
    /// manager's resident set is unchanged, so no node is rebuilt.
    ///
    /// The synchronous work this call can do is bounded by the quickstart
    /// ring, on *every* call and not just the first, so a per-frame
    /// camera-follow (`CYBERPUN-17-7`) cannot turn one frame into a
    /// full-window mount. Note that `streaming.updateCamera` below still
    /// *generates* the whole resident window synchronously; only mounting is
    /// deferred (see this type's doc comment).
    func updateCamera(worldPosition: TilePoint) {
        streaming.updateCamera(worldPosition: worldPosition)
        synchroniseWithResidentChunks(cameraWorldPosition: worldPosition)
    }

    /// Mounts up to `maxChunksPerTick` chunks still waiting in
    /// `pendingMountQueue`, synchronously. `GameScene.update(_:)` calls this
    /// every frame (in Release builds too, not just DEBUG — this is a
    /// correctness fix, not scaffolding) so the chunks `updateCamera`
    /// deferred land over the next few frames rather than never. A no-op once
    /// the queue is empty, so it is always safe to call unconditionally.
    ///
    /// Returns the number of chunks actually mounted this call, mainly for
    /// tests that want to bound how many ticks a full drain takes.
    @discardableResult
    func advanceIncrementalMount(
        maxChunksPerTick: Int = GroundPlaneStreamer.defaultChunksPerIncrementalMountTick
    ) -> Int {
        guard let worldLayer, !pendingMountQueue.isEmpty else { return 0 }

        var mountedThisTick = 0
        while mountedThisTick < maxChunksPerTick, !pendingMountQueue.isEmpty {
            let coordinate = pendingMountQueue.removeFirst()
            // The chunk may have streamed back out of residency (the camera
            // kept moving) before its turn came up, or may already have been
            // mounted by an intervening `updateCamera` call that found it
            // inside the quickstart ring. Either way, skip it rather than
            // double-mount or resurrect an evicted chunk's nodes.
            guard streaming.residentChunks[coordinate] != nil, nodesByChunk[coordinate] == nil else { continue }
            mountChunk(coordinate, into: worldLayer)
            mountedThisTick += 1
        }
        return mountedThisTick
    }

    /// Removes every mounted ground node from the scene graph. Called when a
    /// run ends (or a new one starts with a different seed), so a fresh world
    /// never inherits the previous one's tiles.
    ///
    /// Detached nodes go back into `pool` rather than being dropped: this
    /// call does not touch `streaming`, so `residentChunks` is unchanged and
    /// the next `updateCamera` re-mounts the very same window. Dropping them
    /// would make that re-mount allocate a full resident window's worth of
    /// `SKSpriteNode`s — precisely the churn the pool exists to remove — and
    /// would leave `pool`'s stated invariant false for a supported sequence.
    ///
    /// Also clears `pendingMountQueue`: after every mounted node is torn
    /// down, "pending" is meaningless — the next `updateCamera` re-derives
    /// the whole split (quickstart ring now, remainder queued) from the
    /// camera position it is given.
    func unmountAll() {
        for nodes in nodesByChunk.values {
            for node in nodes {
                node.removeFromParent()
                if pool.count < Self.maxPoolSize {
                    pool.append(node)
                }
            }
        }
        nodesByChunk.removeAll()

        for nodes in buildingNodesByChunk.values {
            for node in nodes {
                node.removeFromParent()
                if buildingPool.count < Self.maxPoolSize {
                    buildingPool.append(node)
                }
            }
        }
        buildingNodesByChunk.removeAll()

        pendingMountQueue.removeAll()
    }

    /// Removes nodes for mounted-but-evicted chunks, mounts the resident
    /// chunks inside the quickstart ring, and queues the resident chunks
    /// outside it for `advanceIncrementalMount()`.
    ///
    /// Eviction runs **before** any mounting so a chunk that streamed out
    /// this call gives its nodes to `pool` in time to be recycled by the
    /// mount (or the drain of what this call queues) — that ordering is what
    /// keeps `pool` bounded by one window's worth (see `pool`'s doc comment)
    /// rather than merely by `maxPoolSize`.
    private func synchroniseWithResidentChunks(cameraWorldPosition: TilePoint) {
        guard let worldLayer else { return }

        // Snapshot the keys: the loop body mutates `nodesByChunk`.
        for coordinate in Array(nodesByChunk.keys) where streaming.residentChunks[coordinate] == nil {
            for node in nodesByChunk[coordinate] ?? [] {
                node.removeFromParent()
                if pool.count < Self.maxPoolSize {
                    pool.append(node)
                }
            }
            nodesByChunk.removeValue(forKey: coordinate)

            // The chunk's buildings go out with it, in the same pass:
            // otherwise an evicted chunk would leave its buildings floating
            // over ground that no longer exists, and the mounted node count
            // would grow with distance roamed.
            for node in buildingNodesByChunk[coordinate] ?? [] {
                node.removeFromParent()
                if buildingPool.count < Self.maxPoolSize {
                    buildingPool.append(node)
                }
            }
            buildingNodesByChunk.removeValue(forKey: coordinate)
        }

        // A chunk queued for the incremental mount that streamed back out of
        // residency before its turn came up must not linger in the queue.
        pendingMountQueue.removeAll { streaming.residentChunks[$0] == nil }

        let cameraChunk = ChunkStreamingManager.chunkCoordinate(containing: cameraWorldPosition)
        let quickstartRing = ChunkStreamingManager.chunkCoordinates(
            withinRadius: ChunkStreamingManager.quickstartRadius,
            of: cameraChunk
        )

        // Anything inside the ring may be on screen right now, so it is
        // mounted in this call even if it was previously queued as an
        // off-screen remainder (the camera has since moved towards it).
        let quickstart = streaming.residentChunks.keys
            .filter { nodesByChunk[$0] == nil && quickstartRing.contains($0) }
        if !quickstart.isEmpty {
            pendingMountQueue.removeAll { quickstartRing.contains($0) }
            for coordinate in quickstart {
                mountChunk(coordinate, into: worldLayer)
            }
        }

        // Everything else is beyond the viewport by construction, so it can
        // land over the next few frames instead of this call — nearest first,
        // so the chunks the camera is most likely to reach next are the ones
        // that arrive soonest.
        let queued = Set(pendingMountQueue)
        let remainder = streaming.residentChunks.keys
            .filter { nodesByChunk[$0] == nil && !quickstartRing.contains($0) && !queued.contains($0) }
            .sorted { chebyshevDistance($0, cameraChunk) < chebyshevDistance($1, cameraChunk) }
        pendingMountQueue.append(contentsOf: remainder)
    }

    /// Chunk-space Chebyshev distance, the same metric `ChunkStreamingManager`
    /// shapes its square windows with — used only to order the incremental
    /// mount queue nearest-first.
    private func chebyshevDistance(_ lhs: ChunkCoordinate, _ rhs: ChunkCoordinate) -> Int {
        max(abs(lhs.x - rhs.x), abs(lhs.y - rhs.y))
    }

    /// Mounts every tile of `coordinate`'s chunk into `worldLayer`, recording
    /// the mounted nodes under `coordinate` in `nodesByChunk`. Assumes
    /// `coordinate` is currently resident and not already mounted — every
    /// call site above checks both before calling this.
    private func mountChunk(_ coordinate: ChunkCoordinate, into worldLayer: SKNode) {
        guard let chunk = streaming.residentChunks[coordinate] else { return }
        var mounted: [SKSpriteNode] = []
        mounted.reserveCapacity(Chunk.size * Chunk.size)
        for localX in 0..<Chunk.size {
            for localY in 0..<Chunk.size {
                let tile = chunk.tile(localX: localX, localY: localY)
                let coordinateOfTile = TileCoordinate(tileX: tile.tileX, tileY: tile.tileY)
                let node = dequeueOrMakeNode(for: tile.kind, at: coordinateOfTile)
                worldLayer.addChild(node)
                mounted.append(node)
            }
        }
        nodesByChunk[coordinate] = mounted

        // `CYBERPUN-17-5-t2`: the buildings this chunk owns, mounted in the
        // same pass and parented just as directly (their `zPosition` is
        // worldLayer-relative too, so an intermediate container would shift
        // the whole depth scheme). `TileFieldRenderer` handles anchor, depth
        // and crispness; this only decides *when* a record becomes a node.
        //
        // `CYBERPUN-17-5-t3`: a building whose lot carries a rooftop sign
        // (`chunk.roofSigns`, keyed here by `carrierLotTile`) gets its sign
        // node attached as a *child* of the building node in this same
        // pass — never tracked in a parallel `[ChunkCoordinate: [SKSpriteNode]]`
        // map of its own, because a child's lifecycle already follows its
        // parent building node's (mount, recycle and eviction) for free.
        var signsByCarrierLot: [TileCoordinate: RooftopSignRecord] = [:]
        for sign in chunk.roofSigns {
            signsByCarrierLot[sign.carrierLotTile] = sign
        }

        var mountedBuildings: [SKSpriteNode] = []
        mountedBuildings.reserveCapacity(chunk.buildingPlacements.count)
        for record in chunk.buildingPlacements {
            let node = dequeueOrMakeBuildingNode(for: record)
            if let sign = signsByCarrierLot[record.lotTile] {
                RooftopSignRenderer.makeSignNode(for: sign, parent: node)
            }
            worldLayer.addChild(node)
            mountedBuildings.append(node)
        }
        buildingNodesByChunk[coordinate] = mountedBuildings
    }

    /// Reuses a pooled node (freed by a chunk that just streamed out) if one
    /// is available, reconfiguring it via `GroundTileRenderer.configure` for
    /// `tileKind`/`coordinateOfTile`; otherwise allocates a fresh node via
    /// `GroundTileRenderer.node(for:at:)`. `pool` only ever holds nodes for
    /// chunks that are no longer resident, so a dequeued node can never
    /// collide with one still mounted for a different chunk.
    private func dequeueOrMakeNode(for tileKind: TileKind, at coordinateOfTile: TileCoordinate) -> SKSpriteNode {
        if let recycled = pool.popLast() {
            GroundTileRenderer.configure(recycled, for: tileKind, at: coordinateOfTile)
            return recycled
        }
        let node = GroundTileRenderer.node(for: tileKind, at: coordinateOfTile)
        node.name = Self.nodeName
        return node
    }

    /// The building-node counterpart of `dequeueOrMakeNode(for:at:)`: reuses
    /// a node freed by an evicted chunk (reconfigured in place by
    /// `TileFieldRenderer.configure`) when one is available, otherwise builds
    /// a fresh one. `buildingPool` only ever holds nodes whose chunk is no
    /// longer resident, so a dequeued node can never still be mounted for a
    /// different record. `TileFieldRenderer` stamps `buildingNodeName` on
    /// both paths, which is how scene audits tell buildings from ground
    /// tiles among `worldLayer`'s children.
    private func dequeueOrMakeBuildingNode(for record: BuildingPlacementRecord) -> SKSpriteNode {
        if let recycled = buildingPool.popLast() {
            // `CYBERPUN-17-5-t3`: a pooled node may still carry a previous
            // occupant's rooftop-sign child (signs are never pooled
            // separately — see `mountChunk`'s doc note). Strip it before
            // `configure` re-textures the building itself, so a recycled
            // node for an unsigned lot never keeps rendering a stale sign,
            // and a recycled node for a *different* signed lot never shows
            // the wrong sign cell underneath the new one `mountChunk` is
            // about to attach.
            recycled.removeAllChildren()
            TileFieldRenderer.configure(recycled, for: record)
            return recycled
        }
        return TileFieldRenderer.makeBuildingNode(for: record)
    }

    /// Name stamped on every mounted ground node, so the scene's audits and
    /// the tests can identify ground tiles among `worldLayer`'s children
    /// without holding a reference to this mount.
    static let nodeName = "groundTile"
}
